---
# base role handlers
- name: Update timezone data
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: Restart ntp
  service:
    name: ntp
    state: restarted
    enabled: yes

- name: Restart smartd
  service:
    name: smartmontools
    state: restarted
    enabled: yes

- name: Restart ssh
  service:
    name: ssh
    state: restarted
    enabled: yes

- name: Restart ufw
  service:
    name: ufw
    state: restarted
    enabled: yes
